-- ============================================================
-- Reference copy of the PROCESSED listings table schema (the
-- output of this pipeline). Kept here so the whole DB schema is
-- versioned alongside the code that reads/writes it.
--
-- IMPORTANT GOTCHA: processed_listings.listing_id is a foreign key
-- to listings.id (the internal auto-increment PK) -- NOT to
-- listings.listing_id (the external site's ad ID). The two columns
-- are easy to confuse because they share a name. src/db/database.py
-- handles this mapping explicitly -- see the comments there.
--
-- This file is documentation/reference -- run it only if the table
-- does not already exist in your database.
-- ============================================================

CREATE TABLE IF NOT EXISTS cars.processed_listings (
    id                                          BIGSERIAL PRIMARY KEY,
    listing_id                                  BIGINT REFERENCES cars.listings(id),
    brand                                       TEXT,
    model                                       TEXT,
    year                                        INTEGER,
    city                                        TEXT,
    mileage                                     BIGINT,
    fuel_type                                   TEXT,
    transmission                                TEXT,
    engine_capacity                             BIGINT,
    body_type                                   TEXT,
    color                                       TEXT,
    registered_in                               TEXT,
    assembly                                    TEXT,
    is_featured                                 BOOLEAN,
    car_age                                     INTEGER,
    mileage_per_year                            DOUBLE PRECISION,
    is_new_car                                  BOOLEAN,
    is_very_old                                 BOOLEAN,
    engine_size_category                        TEXT,
    mileage_category                            TEXT,
    mileage_ratio                               DOUBLE PRECISION,
    is_high_mileage                             BOOLEAN,
    is_low_mileage                              BOOLEAN,
    log_mileage                                 DOUBLE PRECISION,
    log_engine_capacity                         DOUBLE PRECISION,
    feat_alloy_wheels                           BOOLEAN,
    feat_front_speakers                         BOOLEAN,
    feat_immobilizer_key                        BOOLEAN,
    feat_power_locks                            BOOLEAN,
    feat_keyless_entry                          BOOLEAN,
    feat_power_steering                         BOOLEAN,
    feat_air_conditioning                       BOOLEAN,
    feat_infotainment_system                    BOOLEAN,
    feat_rear_speakers                          BOOLEAN,
    feat_steering_switches                      BOOLEAN,
    feat_abs                                    BOOLEAN,
    feat_air_bags                               BOOLEAN,
    feat_rear_camera                            BOOLEAN,
    feat_power_mirrors                          BOOLEAN,
    feat_front_fog_lights                       BOOLEAN,
    feat_led_headlights                         BOOLEAN,
    feat_drls                                   BOOLEAN,
    feat_sun_roof                               BOOLEAN,
    feat_paddle_shifters                        BOOLEAN,
    feat_traction_control                       BOOLEAN,
    feat_front_camera                           BOOLEAN,
    feat_rear_ac_vents                          BOOLEAN,
    feat_climate_control                        BOOLEAN,
    feat_cruise_control                         BOOLEAN,
    feat_push_start                             BOOLEAN,
    feat_power_seats                            BOOLEAN,
    feat_heated_seats                           BOOLEAN,
    feat_android_auto                           BOOLEAN,
    feat_apple_carplay                          BOOLEAN,
    feat_ventilated_seats                       BOOLEAN,
    feat_parking_sensors                        BOOLEAN,
    feat_panoramic_sunroof                      BOOLEAN,
    feat_head_up_display_hud                    BOOLEAN,
    feat_tyre_pressure_monitoring_system_tpms   BOOLEAN,
    feat_360_camera                             BOOLEAN,
    equipment_score                             INTEGER,
    safety_score                                INTEGER,
    comfort_score                                INTEGER,
    luxury_score                                INTEGER,
    technology_score                            INTEGER,
    seller_genuine_condition                    BOOLEAN,
    seller_like_new                             BOOLEAN,
    seller_non_accidental                       BOOLEAN,
    seller_minor_accident                       BOOLEAN,
    seller_minor_touchups                       BOOLEAN,
    seller_engine_repaired                      BOOLEAN,
    seller_engine_swapped                       BOOLEAN,
    seller_sealed_engine                        BOOLEAN,
    seller_service_history                      BOOLEAN,
    seller_authorized_workshop                  BOOLEAN,
    seller_fresh_import                         BOOLEAN,
    seller_original_book                        BOOLEAN,
    seller_duplicate_book                       BOOLEAN,
    seller_original_file                        BOOLEAN,
    seller_duplicate_file                       BOOLEAN,
    seller_missing_file                         BOOLEAN,
    seller_duplicate_plate                      BOOLEAN,
    seller_auction_sheet                        BOOLEAN,
    seller_army_officer                         BOOLEAN,
    seller_driven_on_petrol                     BOOLEAN,
    seller_factory_cng                          BOOLEAN,
    seller_price_negotiable                     BOOLEAN,
    seller_exchange_possible                    BOOLEAN,
    seller_urgent_sale                          BOOLEAN,
    seller_contact_office_hours                 BOOLEAN,
    seller_new_tyres                            BOOLEAN,
    seller_token_paid                           BOOLEAN,
    seller_lifetime_token                       BOOLEAN,
    seller_confidence_score                     INTEGER,
    seller_risk_score                           INTEGER,
    seller_urgency_score                        INTEGER,
    contains_first_owner                        BOOLEAN,
    contains_second_owner                       BOOLEAN,
    contains_single_owner                       BOOLEAN,
    contains_scratch                            BOOLEAN,
    contains_paint                              BOOLEAN,
    contains_touchup                            BOOLEAN,
    contains_accident                           BOOLEAN,
    contains_seal                               BOOLEAN,
    contains_token                              BOOLEAN,
    contains_family_use                         BOOLEAN,
    contains_home_used                          BOOLEAN,
    market_avg_mileage                          DOUBLE PRECISION,
    mileage_difference                          DOUBLE PRECISION,
    market_avg_equipment_score                  DOUBLE PRECISION,
    better_equipped_than_average                BOOLEAN,
    is_large_city                               BOOLEAN,
    city_avg_price                              DOUBLE PRECISION,
    city_listing_count                          BIGINT,
    price                                       BIGINT,
    description                                 TEXT,
    seller_comments                             TEXT,
    price_per_cc                                DOUBLE PRECISION,
    mileage_density                             DOUBLE PRECISION,
    log_price                                   DOUBLE PRECISION,
    market_price_difference                     DOUBLE PRECISION,
    market_price_ratio                          DOUBLE PRECISION,
    percent_below_market                        DOUBLE PRECISION,
    market_avg_price                            DOUBLE PRECISION,
    market_median_price                         DOUBLE PRECISION,
    market_std_price                            DOUBLE PRECISION,
    market_listing_count                        BIGINT
);
