"""
config/column_manifest.py

Single source of truth for:
    1. The exact column names in cars.listings (RAW_LISTINGS_COLUMNS)
    2. The exact column names in cars.processed_listings, grouped the
       same way the feature dictionary groups them (TRAINING_FEATURES,
       TARGET_COLUMN, ANALYSIS_ONLY_COLUMNS)

Every other module in src/features and src/pipeline should import
column *names* from here rather than re-typing them, so a typo or a
schema change only has to be fixed in one place.

This mirrors:
    - sql/01_listings_schema.sql
    - sql/02_processed_listings_schema.sql
    - the feature dictionary ("Feature / Use / How to Obtain" table)
supplied for this project.
"""

# ============================================================
# RAW cars.listings columns (in schema order)
# ============================================================

RAW_LISTINGS_COLUMNS = [
    "id",
    "listing_id",
    "title",
    "brand",
    "model",
    "year",
    "city",
    "mileage",
    "fuel_type",
    "transmission",
    "engine_capacity",
    "color",
    "body_type",
    "price",
    "ad_url",
    "description",
    "seller_comments",
    "scrape_date",
    "registered_in",
    "assembly",
    "is_featured",
    "feat_alloy_wheels",
    "feat_front_speakers",
    "feat_immobilizer_key",
    "feat_power_locks",
    "feat_keyless_entry",
    "feat_power_steering",
    "feat_air_conditioning",
    "feat_infotainment_system",
    "feat_rear_speakers",
    "feat_steering_switches",
    "feat_abs",
    "feat_air_bags",
    "feat_rear_camera",
    "feat_power_mirrors",
    "feat_front_fog_lights",
    "feat_led_headlights",
    "feat_drls",
    "feat_sun_roof",
    "feat_paddle_shifters",
    "feat_traction_control",
    "feat_front_camera",
    "feat_rear_ac_vents",
    "feat_climate_control",
    "feat_cruise_control",
    "feat_push_start",
    "feat_power_seats",
    "feat_heated_seats",
    "feat_android_auto",
    "feat_apple_carplay",
    "feat_ventilated_seats",
    "feat_parking_sensors",
    "feat_panoramic_sunroof",
    "feat_head_up_display_hud",
    "feat_tyre_pressure_monitoring_system_tpms",
    "feat_360_camera",
]

# All feat_* boolean equipment flags scraped directly from the listing.
FEAT_COLUMNS = [c for c in RAW_LISTINGS_COLUMNS if c.startswith("feat_")]

# ============================================================
# cars.processed_listings columns, grouped by intended use.
# (id is autogenerated -- not listed. listing_id is the FK to
# listings.id -- see src/db/database.py for the id vs listing_id
# mapping gotcha.)
# ============================================================

# --- Core attributes carried over (cleaned) from listings ---
CORE_COLUMNS = [
    "brand",
    "model",
    "year",
    "city",
    "mileage",
    "fuel_type",
    "transmission",
    "engine_capacity",
    "body_type",
    "color",
    "registered_in",
    "assembly",
    "is_featured",
]

# --- Derived numeric / categorical features ---
DERIVED_NUMERIC_COLUMNS = [
    "car_age",
    "mileage_per_year",
    "is_new_car",
    "is_very_old",
    "engine_size_category",
    "mileage_category",
    "mileage_ratio",
    "is_high_mileage",
    "is_low_mileage",
    "log_mileage",
    "log_engine_capacity",
]

# --- Equipment / category scores, derived from FEAT_COLUMNS ---
SCORE_COLUMNS = [
    "equipment_score",
    "safety_score",
    "comfort_score",
    "luxury_score",
    "technology_score",
]

# --- Seller keyword flags (from the button -> inserted text -> keyword table) ---
SELLER_FLAG_COLUMNS = [
    "seller_genuine_condition",
    "seller_like_new",
    "seller_non_accidental",
    "seller_minor_accident",
    "seller_minor_touchups",
    "seller_engine_repaired",
    "seller_engine_swapped",
    "seller_sealed_engine",
    "seller_service_history",
    "seller_authorized_workshop",
    "seller_fresh_import",
    "seller_original_book",
    "seller_duplicate_book",
    "seller_original_file",
    "seller_duplicate_file",
    "seller_missing_file",
    "seller_duplicate_plate",
    "seller_auction_sheet",
    "seller_army_officer",
    "seller_driven_on_petrol",
    "seller_factory_cng",
    "seller_price_negotiable",
    "seller_exchange_possible",
    "seller_urgent_sale",
    "seller_contact_office_hours",
    "seller_new_tyres",
    "seller_token_paid",
    "seller_lifetime_token",
]

# --- Seller composite scores, derived from SELLER_FLAG_COLUMNS ---
SELLER_SCORE_COLUMNS = [
    "seller_confidence_score",
    "seller_risk_score",
    "seller_urgency_score",
]

# --- Free-text "contains_*" flags (broader than the seller button flags) ---
CONTAINS_COLUMNS = [
    "contains_first_owner",
    "contains_second_owner",
    "contains_single_owner",
    "contains_scratch",
    "contains_paint",
    "contains_touchup",
    "contains_accident",
    "contains_seal",
    "contains_token",
    "contains_family_use",
    "contains_home_used",
]

# --- Market comparison features that are safe to train on (no price used) ---
MARKET_TRAINING_COLUMNS = [
    "market_avg_mileage",
    "mileage_difference",
    "market_avg_equipment_score",
    "better_equipped_than_average",
]

# --- Location features ---
LOCATION_COLUMNS = [
    "is_large_city",
    "city_avg_price",
    "city_listing_count",
]

# --- Target ---
TARGET_COLUMN = "price"

# --- Analysis-only columns: kept in processed_listings for exploration /
#     reporting, but MUST NOT be fed into the price model. Several of
#     these are computed directly from price (or an aggregate of price)
#     for the row's own market segment, so using them as model inputs
#     would leak the target. ---
ANALYSIS_ONLY_COLUMNS = [
    "description",
    "seller_comments",
    "price_per_cc",
    "mileage_density",
    "log_price",
    "market_price_difference",   # leakage risk: derived from price
    "market_price_ratio",        # leakage risk: derived from price
    "percent_below_market",      # leakage risk: derived from price
    "market_avg_price",          # leakage risk: derived from price
    "market_median_price",       # leakage risk: derived from price
    "market_std_price",          # leakage risk: derived from price
    "market_listing_count",
]

# --- The full set of columns that are safe to hand to a model ---
TRAINING_FEATURES = (
    CORE_COLUMNS
    + DERIVED_NUMERIC_COLUMNS
    + FEAT_COLUMNS
    + SCORE_COLUMNS
    + SELLER_FLAG_COLUMNS
    + SELLER_SCORE_COLUMNS
    + CONTAINS_COLUMNS
    + MARKET_TRAINING_COLUMNS
    + LOCATION_COLUMNS
)

# --- Full column order written to cars.processed_listings (excludes the
#     autogenerated `id`; `listing_id` is added separately by the
#     pipeline since it isn't "computed" by any single feature module) ---
PROCESSED_LISTINGS_COLUMNS = (
    ["listing_id"]
    + CORE_COLUMNS
    + DERIVED_NUMERIC_COLUMNS
    + FEAT_COLUMNS
    + SCORE_COLUMNS
    + SELLER_FLAG_COLUMNS
    + SELLER_SCORE_COLUMNS
    + CONTAINS_COLUMNS
    + MARKET_TRAINING_COLUMNS
    + LOCATION_COLUMNS
    + [TARGET_COLUMN]
    + ANALYSIS_ONLY_COLUMNS
)


def assert_no_duplicates():
    """Sanity check used by tests: no column should appear twice."""
    seen = set()
    dupes = set()
    for col in PROCESSED_LISTINGS_COLUMNS:
        if col in seen:
            dupes.add(col)
        seen.add(col)
    if dupes:
        raise ValueError(f"Duplicate columns in manifest: {sorted(dupes)}")
    return True
