-- ============================================================
-- Reference copy of the RAW listings table schema (source data,
-- populated by the scraper). Kept here so the whole DB schema is
-- versioned alongside the code that reads/writes it.
-- This file is documentation/reference -- run it only if the table
-- does not already exist in your database.
-- ============================================================

CREATE TABLE IF NOT EXISTS cars.listings (
    id                  BIGSERIAL PRIMARY KEY,
    listing_id          BIGINT UNIQUE,
    title               TEXT,
    brand               TEXT,
    model               TEXT,
    year                SMALLINT,
    city                TEXT,
    mileage             INTEGER,
    fuel_type           TEXT,
    transmission        TEXT,
    engine_capacity     INTEGER,
    color               TEXT,
    body_type           TEXT,
    price               INTEGER,
    ad_url              TEXT,
    description         TEXT,
    seller_comments     TEXT,
    scrape_date         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    registered_in       TEXT,
    assembly            TEXT,
    is_featured         BOOLEAN,
    feat_alloy_wheels                          BOOLEAN,
    feat_front_speakers                        BOOLEAN,
    feat_immobilizer_key                       BOOLEAN,
    feat_power_locks                           BOOLEAN,
    feat_keyless_entry                         BOOLEAN,
    feat_power_steering                        BOOLEAN,
    feat_air_conditioning                      BOOLEAN,
    feat_infotainment_system                   BOOLEAN,
    feat_rear_speakers                         BOOLEAN,
    feat_steering_switches                     BOOLEAN,
    feat_abs                                   BOOLEAN,
    feat_air_bags                              BOOLEAN,
    feat_rear_camera                           BOOLEAN,
    feat_power_mirrors                         BOOLEAN,
    feat_front_fog_lights                      BOOLEAN,
    feat_led_headlights                        BOOLEAN,
    feat_drls                                  BOOLEAN,
    feat_sun_roof                               BOOLEAN,
    feat_paddle_shifters                       BOOLEAN,
    feat_traction_control                      BOOLEAN,
    feat_front_camera                          BOOLEAN,
    feat_rear_ac_vents                         BOOLEAN,
    feat_climate_control                       BOOLEAN,
    feat_cruise_control                        BOOLEAN,
    feat_push_start                            BOOLEAN,
    feat_power_seats                           BOOLEAN,
    feat_heated_seats                          BOOLEAN,
    feat_android_auto                          BOOLEAN,
    feat_apple_carplay                         BOOLEAN,
    feat_ventilated_seats                      BOOLEAN,
    feat_parking_sensors                       BOOLEAN,
    feat_panoramic_sunroof                     BOOLEAN,
    feat_head_up_display_hud                   BOOLEAN,
    feat_tyre_pressure_monitoring_system_tpms  BOOLEAN,
    feat_360_camera                            BOOLEAN
);
